version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sales-analytics-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sales-analytics
    volumes:
      - mongodb_data:/data/db
    networks:
      - sales-network

  # Backend API Server
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sales-analytics-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sales-analytics
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - sales-network

  # Frontend Application
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: sales-analytics-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - sales-network

volumes:
  mongodb_data:
    driver: local

networks:
  sales-network:
    driver: bridge 