version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sales-analytics-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sales-analytics
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - sales-network-dev

  # Backend API Server (Development)
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: sales-analytics-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sales-analytics
      - PORT=5001
      - NODE_ENV=development
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - sales-network-dev
    command: npm run dev

  # Frontend Application (Development)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: sales-analytics-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - NODE_ENV=development
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - sales-network-dev
    command: npm run dev

volumes:
  mongodb_data_dev:
    driver: local

networks:
  sales-network-dev:
    driver: bridge 